# Generated by Django 4.1.5 on 2023-01-20 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cookie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StoreCookie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "cookie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="CookieInStore",
                        to="bakery.cookie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frozen_ct", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("date_frozen", models.DateField(auto_now=True)),
                (
                    "cookie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bakery.cookie"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Baked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frozen_ct", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("date_baked", models.DateField(auto_now=True)),
                (
                    "cookie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bakery.cookie"
                    ),
                ),
            ],
        ),
    ]
