# Generated by Django 4.1.5 on 2023-01-20 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0002_storecookie_last_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storecookie",
            name="last_updated",
        ),
    ]
