# Generated by Django 4.1.5 on 2023-01-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0003_remove_storecookie_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="storecookie",
            name="last_updated",
            field=models.DateField(auto_now=True),
        ),
    ]
