# Generated by Django 4.1.5 on 2023-01-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0004_storecookie_last_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baked",
            old_name="frozen_ct",
            new_name="quantity",
        ),
        migrations.AddField(
            model_name="baked",
            name="status",
            field=models.CharField(
                choices=[("P", "Packaged"), ("F", "Frozen")], default="F", max_length=1
            ),
        ),
    ]
