# Generated by Django 4.1.5 on 2023-01-20 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0005_rename_frozen_ct_baked_quantity_baked_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baked",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bakery.cookie"
            ),
        ),
        migrations.AlterField(
            model_name="dough",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bakery.cookie"
            ),
        ),
        migrations.AlterField(
            model_name="storecookie",
            name="cookie",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="CookieInStore",
                to="bakery.cookie",
            ),
        ),
    ]
