# Generated by Django 4.1.5 on 2023-01-20 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0006_alter_baked_cookie_alter_dough_cookie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baked",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bakery.cookie"
            ),
        ),
        migrations.AlterField(
            model_name="dough",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bakery.cookie"
            ),
        ),
        migrations.AlterField(
            model_name="storecookie",
            name="cookie",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="CookieInStore",
                to="bakery.cookie",
            ),
        ),
    ]
