# Generated by Django 4.1.5 on 2023-01-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0007_alter_baked_cookie_alter_dough_cookie_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baked",
            options={"ordering": ["cookie"]},
        ),
        migrations.AlterModelOptions(
            name="cookie",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="dough",
            options={"ordering": ["cookie"]},
        ),
        migrations.AlterModelOptions(
            name="storecookie",
            options={"ordering": ["cookie"]},
        ),
        migrations.RenameField(
            model_name="dough",
            old_name="frozen_ct",
            new_name="quantity",
        ),
    ]
