# Generated by Django 4.1.5 on 2023-01-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0009_alter_baked_options_alter_dough_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookie",
            name="par",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="storecookie",
            name="par",
            field=models.IntegerField(null=True),
        ),
    ]
