# Generated by Django 4.1.5 on 2023-01-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0010_cookie_par_storecookie_par"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cookie",
            old_name="par",
            new_name="baked_cookie_par",
        ),
        migrations.AddField(
            model_name="cookie",
            name="dough_par",
            field=models.IntegerField(null=True),
        ),
    ]
