# Generated by Django 4.1.5 on 2023-01-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0011_rename_par_cookie_baked_cookie_par_cookie_dough_par"),
    ]

    operations = [
        migrations.AddField(
            model_name="baked",
            name="mini",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "N")], default="N", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="baked",
            name="location",
            field=models.CharField(
                choices=[
                    ("T", "Top Freezer"),
                    ("B", "Bottom Freezer"),
                    ("R", "Refrigerator"),
                    ("SF", "Storage Freezer"),
                    ("SR", "Storage Refrigerator"),
                ],
                default="T",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="dough",
            name="location",
            field=models.CharField(
                choices=[
                    ("T", "Top Freezer"),
                    ("B", "Bottom Freezer"),
                    ("R", "Refrigerator"),
                    ("SF", "Storage Freezer"),
                    ("SR", "Storage Refrigerator"),
                ],
                default="T",
                max_length=2,
            ),
        ),
    ]
