# Generated by Django 4.1.5 on 2023-01-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0012_baked_mini_alter_baked_location_alter_dough_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baked",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
    ]
