# Generated by Django 4.1.5 on 2023-01-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0014_alter_baked_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baked",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
