# Generated by Django 4.1.5 on 2023-01-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0015_alter_baked_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baked",
            name="mini",
        ),
        migrations.CreateModel(
            name="Mini",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Packaged"), ("F", "Frozen")],
                        default="F",
                        max_length=1,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("T", "Top Freezer"),
                            ("B", "Bottom Freezer"),
                            ("R", "Refrigerator"),
                            ("SF", "Storage Freezer"),
                            ("SR", "Storage Refrigerator"),
                        ],
                        default="T",
                        max_length=2,
                    ),
                ),
                ("date_baked", models.DateField(auto_now=True)),
                (
                    "cookie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bakery.cookie"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mini Cookie",
                "ordering": ["cookie"],
            },
        ),
    ]
