# Generated by Django 4.1.5 on 2023-01-30 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0016_remove_baked_mini_mini"),
    ]

    operations = [
        migrations.AddField(
            model_name="storecookie",
            name="type",
            field=models.CharField(
                choices=[("L", "Mega"), ("S", "Mini")], default="L", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="storecookie",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bakery.cookie"
            ),
        ),
    ]
