# Generated by Django 4.1.5 on 2023-01-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0017_storecookie_type_alter_storecookie_cookie"),
    ]

    operations = [
        migrations.AddField(
            model_name="baked",
            name="type",
            field=models.CharField(
                choices=[("L", "Mega"), ("S", "Mini")], default="L", max_length=1
            ),
        ),
        migrations.DeleteModel(
            name="Mini",
        ),
    ]
