# Generated by Django 4.1.5 on 2023-01-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0018_baked_type_delete_mini"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookie",
            name="mini_cookie_par",
            field=models.IntegerField(null=True),
        ),
    ]
