# Generated by Django 4.1.5 on 2023-02-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0020_rename_type_baked_size_rename_type_storecookie_size"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cookie",
            old_name="baked_cookie_par",
            new_name="mega_cookie_par",
        ),
    ]
