# Generated by Django 4.1.6 on 2023-02-15 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0021_rename_baked_cookie_par_cookie_mega_cookie_par"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baked",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bakery.cookie"
            ),
        ),
        migrations.AlterField(
            model_name="dough",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bakery.cookie"
            ),
        ),
        migrations.AlterField(
            model_name="storecookie",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bakery.cookie"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storecookie",
            unique_together={("size", "cookie")},
        ),
    ]
