# Generated by Django 4.1.7 on 2023-02-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0022_alter_baked_cookie_alter_dough_cookie_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
