# Generated by Django 4.1.7 on 2023-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0023_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baked",
            name="quantity",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="cookie",
            name="dough_par",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="dough",
            name="quantity",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="storecookie",
            name="par",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="storecookie",
            name="quantity",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
